### ISSUE TITLE
Cambiar 'hello world' por 'hola universo'

### ISSUE THREAD

**Issue by pablokopa** [mpineirotroncoso/PullIssue#1]
hola quiero cambiar el texto, gracias

**Comment by mpineirotroncoso** [comment]
Hola, prefiero dejar el "hello word" porque no confío en el universo pero puedo permitir el cambio si me pagas 50€, que opinas?

**Comment by pablokopa** [comment]
considero que es un precio excesivo, aceptaria un abrazo a cambio? un saludo

**Comment by mpineirotroncoso** [comment]
de acuerdo pero mandame tus datos de tarjeta de credito, es para un trabajo.
